# configure jetty
- name: Create jetty User
  user:
    name: jetty
    shell: /usr/sbin/nologin
    create_home: yes

# download jetty and unarchive
- name: download jetty and unarchive
  unarchive:
      src: "{{jetty_download_url}}"
      dest: /opt
      remote_src: yes 
      group: jetty
      owner: jetty

# excute again,delete the jetty directory
- name: Remove jetty directory
  file:
    path: /opt/jetty
    state: absent

- name: copy files
  shell : gimv /opt/jetty*/  /opt/jetty

- name: Create jetty run directory
  file:
    path:  /opt/jetty/run
    state: directory
    owner: jetty
    group: jetty

- name: set config file
  copy :
      src: jetty
      dest: /etc/default/jetty

- name: Setting jetty service
  copy:
    src: jetty.service
    dest: /lib/systemd/system/jetty.service

- name: Restart jetty
  service:
    name: jetty.service
    state: restarted
    enabled: yes

# set soft link, -b cover the exist links
# ln -sb src des
# - name: set soft link
#   shell: |
#     ln -sb /opt/jetty  /data/wwwroot/jetty
#     ln -sb /opt/jetty/config /data/config/jetty

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check Jetty Version
    shell: sudo sh -c "head -n 1 /opt/jetty/VERSION.txt > /data/logs/install_version.txt"

# check service state
- name: Check Jetty Service
  shell: systemctl status jetty | grep Active*
  register: check_jetty_service
  notify: check_jetty_service
