# install Jetty by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure Jetty

- name: Create jetty User
  user:
    name: jetty
    shell: /usr/sbin/nologin
    home: /data/wwwroot/jetty
    create_home: no

- name: Create jetty directory
  file:
    path: /data/wwwroot/jetty
    state: directory
    owner: jetty
    group: jetty
    
- name: Download jetty
  get_url:
    dest: /data/wwwroot/jetty
    url: "{{rabbitmq_download_url}}"
    owner: jetty
    group: jetty

- name: Set jetty config
  template:
    src: jetty.conf.jinja2
    dest: /data/wwwroot/jetty/jetty.conf
    owner: jetty
    group: jetty

- name: Setting jetty service
  copy:
    src: jetty.service
    dest: /lib/systemd/system/jetty.service

- name: Restart jetty
  service:
    name: jetty.service
    state: restarted
    enabled: yes

- name: Create jetty System User
  user:
      name: jetty 
      create_home: no 
      home: /opt/jetty
      shell: /usr/sbin/nologin

- name: Download jetty
  unarchive:
      src: "{{rabbitmq_download_url}}"
      dest: /opt/ 
      group: jetty 
      remote_src: yes
      owner: jetty
      mode: g+w

- name: Create the storage directory for files.
  file:
      path: /opt/jetty/data
      state: directory 
      owner: jetty 
      group: jetty
      mode: g+w
      
- name: Set database connection /opt/jetty/config/config.json
  lineinfile:
    dest: /opt/jetty/config/config.json
    regexp: '"DataSource":'
    line: '    "DataSource": "{{rabbitmq_db_user}}:{{rabbitmq_db_password}}@tcp(localhost:3306)/{{rabbitmq_db_name}}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",'
    backrefs: yes 

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /opt/jetty  /data/wwwroot/jetty
    ln -sb /opt/jetty/config /data/config/jetty

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check Jetty Version
    shell: sudo sh -c "rabbitmqctl status | grep 'Jetty version' 1>> /data/logs/install_version.txt"

  - name: Check Erlang Version
    shell: sudo sh -c 'echo "Erlang $(yum info erlang | grep Version | sed -n 1p)" 1>> /data/logs/install_version.txt'
    when: ansible_os_family=="RedHat"

# check service state
- name: Check Jetty Service
  shell: systemctl status jetty | grep Active*
  register: check_rabbitmq_service
  notify: check_rabbitmq_service
